name: p_limit
description: Run multiple promise-returning & async functions with limited concurrency.
version: 1.0.1
repository: https://github.com/hunterwilhelm/p_limit
homepage: https://github.com/hunterwilhelm/p_limit
issue_tracker: https://github.com/hunterwilhelm/p_limit/issues

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
